name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Step
        run: echo "Deploying application to staging server..."

      - name: Use Secret
        run: echo "Key = ${{ secrets.DEPLOY_KEY }}"
